In [13]:
import os
import tweepy as tw
import pandas as pd

In [14]:
consumer_key = 'vezezGSjD1a8ayKiD2f66tRfD'
consumer_secret = 'OpCrhVSsGY2sqlko4w6bcj07Wheq9wApLRyvcYIvMTjzAnMPbv'
access_token = '1475282070339391489-rKunMuAUHDba2RyL5lEoDFYEGc453Z'
access_token_secret = 'BV4bF17lOeeBSflQtYBJwpYeMP1mmL3qPGOeNAjhjqM9y'

In [15]:
auth = tw.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth, wait_on_rate_limit=True)

In [16]:
# Define the search term and the date_since date as variables
search_words = "GOT7"
date_since = "2020-01-01"

In [17]:
# Collect tweets
tweets = tw.Cursor(api.search,
              q=search_words,
              lang="id",
              since=date_since).items(10)

# Iterate and print tweets
tweets_copy = []
for tweet in tweets:
    tweets_copy.append(tweet)

In [18]:
import pandas as pd
# intialize the dataframe
tweets_df = pd.DataFrame()

In [19]:
# for tweet in tweets_copy:
#     hashtags = []
#     mention = []
    
#     text = api.get_status(id=tweet.id, tweet_mode='extended').full_text

#     for mention in tweet.entities["user_mentions"]:
      
#       print(tweet.entities["user_mentions"][0].get('screen_name'))

In [20]:
for tweet in tweets_copy:
    hashtags = []
    mention = []
    try:
        text = api.get_status(id=tweet.id, tweet_mode='extended').full_text
        author = api.get_status(id=tweet.id, tweet_mode='extended').retweeted_status.author.screen_name

        for hashtag in tweet.entities["hashtags"]:
            hashtags.append(hashtag["text"])
        for mention in tweet.entities["user_mentions"]:
            mention.append(tweet.entities["user_mentions"][0].get('screen_name'))
        
    except:
        pass
    
    tweets_df = tweets_df.append(pd.DataFrame({'user_name': tweet.user.screen_name,
                                               'nama' : tweet.user.name,
                                               'id' : tweet.user.id,
                                               'retweet_count' : tweet.retweet_count,
                                               'author' : author,
                                               'mention' :[mention['screen_name'] if mention else None],
                                               'date': tweet.created_at,
                                               'text': text, 
                                               'hashtags': [hashtags if hashtags else None],
                                               'source': tweet.source}))
    tweets_df = tweets_df.reset_index(drop=True)

In [21]:
  tweets_df

        user_name  ...               source
0       wolseriin  ...  Twitter for Android
1     IGOT7INTHAI  ...  Twitter for Android
2      HjhjkGuswl  ...         twittbot.net
3  putri_ayuandii  ...              dlvr.it
4       AkangOnce  ...  Twitter for Android
5          1a2704  ...  Twitter for Android
6        pqirsdef  ...  Twitter for Android
7        flyfly45  ...         twittbot.net
8      nuonuo11xd  ...  Twitter for Android
9       arielmks2  ...         twittbot.net

[10 rows x 10 columns]